### ISSUE TITLE
新版更新后不会设置页面请求header 头了

### ISSUE THREAD

**Issue by yangweijie** [NHZEX/socket-log-chrome#3]
加不加 * 域名规则 都一样，不会在header头里传 tabid 等字符串了。

**Comment by NHZEX** [comment]
1. 浏览器对`mv2`模式的扩展即将弃用，`mv3`模式下`tabId`没有好方法获取并设置，当前策略只能转发到最后活动的焦点页面。
2. 如果一条规则都不填则默认全部请求都需要处理

当前规则写法例子是：
```
*://localhost
*://127.0.0.1
*://*:test
*://192.168.*
```
提供一下截图看规则是否有问题。新版你是通过哪种方式安装的？

**Comment by NHZEX** [comment]
如果仍然想用默认全局注入与tabId支持，在浏览器停止支持`mv2`前可以继续旧版，已经标记 [v2.1.1](https://github.com/NHZEX/socket-log-chrome/releases/tag/v2.1.1)

如需继续反馈新版问题，可以重新打开。

**Comment by NHZEX** [comment]
问题已发现：
当前'mv3'版本无法同步采集`tabId`情况下会传递`tabId=0`，与当前版本接受端产生兼容性问题。
因为我平时都是使用`force_client_ids`所以这个问题一直没发现。

当前的解决办法以下选项：

1. 服务端使用`force_client_ids`推送日志。
2. 使用最新版扩展 [v3.1.0](https://github.com/NHZEX/socket-log-chrome/releases/tag/v3.1.0)，传递假值`999999`。（v3版本只建议使用新版服务端，`nodejs`版不保证迭代兼容性）

PS：
1. 后续调整服务端处理`tagId=0`逻辑的逻辑。
2. 如果使用了新版服务端（>=2.2.1）与框架端（或者自己改一下原框架`Socket`的代码），建议切换传输传递模式为`client_id_send_method = query 或 header`，更好的支持之前提过的反代部署方案，简化反代配置。
