### ISSUE TITLE
新版本的Edge浏览器 用不了了 【版本 130.0.2849.56 (正式版本) (arm64)】

### ISSUE THREAD

**Issue by phpluo** [NHZEX/socket-log-chrome#4]
![image](https://github.com/user-attachments/assets/28f3f10c-5c56-44fc-912b-d30b47238aac)

**Comment by NHZEX** [comment]
这个兼容问题目前可以解压这个版本本地载入：

https://github.com/NHZEX/socket-log-chrome/releases/download/v4.0.4/release.v4.0.4.zip

应用市场审核需要时间
